apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/joshua-armory/eap
  ref:
    branch: main
 ignore: |
    # exclude all
    !/cluster/deploy.yml
