apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-app
  namespace: joshua-operspin
spec:
  interval: 5m
  url: https://github.com/joshua-armory/eap
  ref:
    branch: main
