apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 15m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app
